#!/usr/bin/with-contenv bash

cd $HOME
chmod 777 /defaults && chmod a+x /defaults/startwm.sh
chown polaris:polaris /home/polaris
echo "Démarrage WM"
exec s6-setuidgid polaris /bin/bash /defaults/startwm.sh
